/// Evidence pack PDF generator — 법적 제출용 증거 팩 PDF 생성.
///
/// 구성:
/// 1. 표지 (사건명·작성자·생성일·사진수·해시 알고리즘)
/// 2. NTP + 해시 체인 설명 블록
/// 3. 각 사진 페이지 (썸네일 + 메타데이터 표 + 전체 해시)
/// 4. 외부 검증 방법 안내
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'package:exacta/data/database.dart';

class EvidencePackService {
  EvidencePackService._();

  /// 생성 → 임시 디렉토리에 저장된 PDF 파일 경로 반환.
  /// CJK(한/일) 문자 지원을 위해 Google Fonts의 Noto Sans를 로드.
  /// 네트워크 실패 시 기본 폰트로 fallback (ASCII만 정상 표시).
  static Future<String> generate({
    required List<Photo> photos,
    required String caseName,
    required String author,
    required EvidencePackStrings strings,
  }) async {
    // CJK 폰트 로드 — 실패 시 기본 폰트 사용
    pw.ThemeData? theme;
    try {
      final base = await PdfGoogleFonts.notoSansRegular();
      final bold = await PdfGoogleFonts.notoSansBold();
      final krFallback = await PdfGoogleFonts.notoSansKRRegular();
      final jpFallback = await PdfGoogleFonts.notoSansJPRegular();
      theme = pw.ThemeData.withFont(
        base: base,
        bold: bold,
        fontFallback: [krFallback, jpFallback],
      );
    } catch (e) {
      debugPrint('PdfGoogleFonts load failed, using default: $e');
    }

    final pdf = pw.Document(theme: theme);
    final generatedAt = DateTime.now();
    final generatedAtStr = _formatDateTime(generatedAt);

    // ── 1. 표지 페이지 ──
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(48),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // 타이틀
            pw.Container(
              padding: const pw.EdgeInsets.only(bottom: 16),
              decoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(color: PdfColors.black, width: 2),
                ),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    strings.cover,
                    style: pw.TextStyle(
                      fontSize: 32,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'EXACTA · SHA-256 Hash Chain',
                    style: const pw.TextStyle(
                      fontSize: 11,
                      color: PdfColors.grey600,
                      letterSpacing: 1.0,
                    ),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 40),

            // 메타 표
            _metaRow(strings.caseName, caseName),
            _metaRow(strings.author, author),
            _metaRow(strings.generatedAt, generatedAtStr),
            _metaRow(strings.photoCount, photos.length.toString()),
            _metaRow(strings.hashAlgo, 'SHA-256 (RFC 6234)'),

            pw.SizedBox(height: 40),

            // NTP + 체인 설명
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Text(
                strings.ntpNote,
                style: const pw.TextStyle(
                  fontSize: 10,
                  lineSpacing: 3,
                  color: PdfColors.grey800,
                ),
              ),
            ),

            pw.Spacer(),
            pw.Center(
              child: pw.Text(
                'Generated by Exacta',
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey500,
                ),
              ),
            ),
          ],
        ),
      ),
    );

    // ── 2. 각 사진 페이지 ──
    for (var i = 0; i < photos.length; i++) {
      final photo = photos[i];
      pw.Widget imageWidget;
      try {
        final file = File(photo.filePath);
        if (await file.exists()) {
          final bytes = await file.readAsBytes();
          imageWidget = pw.Image(
            pw.MemoryImage(bytes),
            height: 260,
            fit: pw.BoxFit.contain,
          );
        } else {
          imageWidget = _missingImage();
        }
      } catch (_) {
        imageWidget = _missingImage();
      }

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                strings.photoTitle(i + 1),
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 12),
              pw.Center(child: imageWidget),
              pw.SizedBox(height: 16),
              _metaRow(strings.timestamp, _formatTimestamp(photo.timestamp),
                  mono: true),
              if (photo.latitude != null && photo.longitude != null)
                _metaRow(
                  strings.gps,
                  '${photo.latitude!.toStringAsFixed(7)}, ${photo.longitude!.toStringAsFixed(7)}',
                  mono: true,
                ),
              if (photo.address != null && photo.address!.isNotEmpty)
                _metaRow(strings.address, photo.address!),
              if (photo.memo != null && photo.memo!.isNotEmpty)
                _metaRow(strings.memo, photo.memo!),
              pw.SizedBox(height: 12),
              // 해시 블록
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.circular(6),
                  border: pw.Border.all(color: PdfColors.grey300),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _hashLine(strings.photoHash, photo.photoHash),
                    pw.SizedBox(height: 4),
                    _hashLine(strings.chainHash, photo.chainHash),
                    pw.SizedBox(height: 4),
                    _hashLine(strings.prevHash,
                        photo.prevHash ?? 'GENESIS BLOCK'),
                  ],
                ),
              ),
              pw.Spacer(),
              pw.Text(
                'Photo ${i + 1} / ${photos.length}   ·   ${photo.photoCode ?? ''}',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ),
      );
    }

    // ── 3. 외부 검증 방법 페이지 ──
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(48),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              strings.verifyTitle,
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 20),
            for (final step in [
              strings.verifyStep1,
              strings.verifyStep2,
              strings.verifyStep3,
              strings.verifyStep4,
            ])
              pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 12),
                child: pw.Text(
                  step,
                  style: const pw.TextStyle(
                    fontSize: 11,
                    lineSpacing: 3,
                  ),
                ),
              ),
          ],
        ),
      ),
    );

    // ── 4. 파일 저장 ──
    final tempDir = await getTemporaryDirectory();
    final safe = _sanitize(caseName);
    final ds = '${generatedAt.year}${_pad(generatedAt.month)}${_pad(generatedAt.day)}';
    final fileName = 'exacta_evidence_${safe}_$ds.pdf';
    final filePath = p.join(tempDir.path, fileName);
    await File(filePath).writeAsBytes(await pdf.save());

    return filePath;
  }

  // ── 헬퍼 ────────────────────────────────────────────────────

  static pw.Widget _metaRow(String label, String value, {bool mono = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 110,
            child: pw.Text(
              label,
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey600,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _hashLine(String label, String? hash) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(
          width: 110,
          child: pw.Text(
            label,
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
            ),
          ),
        ),
        pw.Expanded(
          child: pw.Text(
            hash ?? 'N/A',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.black,
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _missingImage() {
    return pw.Container(
      height: 260,
      width: double.infinity,
      color: PdfColors.grey200,
      alignment: pw.Alignment.center,
      child: pw.Text(
        'Image not available',
        style: const pw.TextStyle(color: PdfColors.grey500),
      ),
    );
  }

  static String _formatTimestamp(String iso) {
    final dt = DateTime.tryParse(iso);
    if (dt == null) return iso;
    return '${dt.year}-${_pad(dt.month)}-${_pad(dt.day)}  ${_pad(dt.hour)}:${_pad(dt.minute)}:${_pad(dt.second)}';
  }

  static String _formatDateTime(DateTime dt) {
    return '${dt.year}-${_pad(dt.month)}-${_pad(dt.day)}  ${_pad(dt.hour)}:${_pad(dt.minute)}:${_pad(dt.second)}';
  }

  static String _pad(int n) => n.toString().padLeft(2, '0');

  static String _sanitize(String name) {
    final cleaned = name
        .replaceAll(RegExp(r'[^\w가-힣一-龥ぁ-んァ-ヶー]'), '_')
        .replaceAll(RegExp(r'_{2,}'), '_');
    return cleaned.isEmpty ? 'case' : cleaned;
  }
}

/// PDF 위젯은 BuildContext를 쓸 수 없으므로 문자열을 외부에서 주입.
class EvidencePackStrings {
  final String cover;
  final String caseName;
  final String author;
  final String generatedAt;
  final String photoCount;
  final String hashAlgo;
  final String ntpNote;
  final String Function(int index) photoTitle;
  final String timestamp;
  final String gps;
  final String address;
  final String project;
  final String memo;
  final String photoHash;
  final String chainHash;
  final String prevHash;
  final String verifyTitle;
  final String verifyStep1;
  final String verifyStep2;
  final String verifyStep3;
  final String verifyStep4;

  const EvidencePackStrings({
    required this.cover,
    required this.caseName,
    required this.author,
    required this.generatedAt,
    required this.photoCount,
    required this.hashAlgo,
    required this.ntpNote,
    required this.photoTitle,
    required this.timestamp,
    required this.gps,
    required this.address,
    required this.project,
    required this.memo,
    required this.photoHash,
    required this.chainHash,
    required this.prevHash,
    required this.verifyTitle,
    required this.verifyStep1,
    required this.verifyStep2,
    required this.verifyStep3,
    required this.verifyStep4,
  });
}
