/// PDF report generator - cover + 2 photos/page with metadata
import 'dart:io';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'package:exacta/data/database.dart';

class PdfReportService {
  /// 로케일별 고정 문자열 — pdf 위젯은 BuildContext를 사용할 수 없으므로 분리
  static Map<String, String> _strings(String locale) {
    return switch (locale) {
      'ko' => {
          'photos': '장의 사진',
          'generatedBy': 'Exacta로 생성',
          'notAvailable': '이미지 없음',
          'weather': '날씨',
        },
      'ja' => {
          'photos': '枚の写真',
          'generatedBy': 'Exactaで生成',
          'notAvailable': '画像なし',
          'weather': '天気',
        },
      _ => {
          'photos': 'photos',
          'generatedBy': 'Generated by Exacta',
          'notAvailable': 'Image not available',
          'weather': 'Weather',
        },
    };
  }

  /// 프로젝트 사진 리포트 PDF 생성 → 파일 경로 반환
  static Future<String> generate({
    required List<Photo> photos,
    String projectName = 'Exacta Report',
    String locale = 'en',
  }) async {
    final s = _strings(locale);
    final pdf = pw.Document();

    // 표지
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Center(
          child: pw.Column(
            mainAxisAlignment: pw.MainAxisAlignment.center,
            children: [
              pw.Text(projectName,
                  style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 16),
              pw.Text(
                locale == 'en'
                    ? '${photos.length} ${s['photos']}'
                    : '${photos.length}${s['photos']}',
                style: const pw.TextStyle(fontSize: 16, color: PdfColors.grey600),
              ),
              pw.SizedBox(height: 8),
              pw.Text(DateTime.now().toIso8601String().substring(0, 10),
                  style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey400)),
              pw.SizedBox(height: 40),
              pw.Text(s['generatedBy']!,
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey400)),
            ],
          ),
        ),
      ),
    );

    // 사진 페이지 (2장씩)
    for (var i = 0; i < photos.length; i += 2) {
      final batch = photos.skip(i).take(2).toList();
      final widgets = <pw.Widget>[];

      for (final photo in batch) {
        final file = File(photo.filePath);
        if (!await file.exists()) continue;

        pw.Widget? imageWidget;
        try {
          final bytes = await file.readAsBytes();
          final image = pw.MemoryImage(bytes);
          imageWidget = pw.Image(image, height: 250, fit: pw.BoxFit.contain);
        } catch (e) {
          imageWidget = pw.Container(
            height: 250,
            color: PdfColors.grey200,
            child: pw.Center(child: pw.Text(s['notAvailable']!)),
          );
        }

        widgets.add(
          pw.Container(
            margin: const pw.EdgeInsets.only(bottom: 16),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                imageWidget,
                pw.SizedBox(height: 8),
                pw.Row(
                  children: [
                    pw.Expanded(
                      child: pw.Text(
                        photo.timestamp.substring(0, 19).replaceAll('T', ' '),
                        style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
                      ),
                    ),
                    if (photo.photoCode != null)
                      pw.Text(photo.photoCode!,
                          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                  ],
                ),
                if (photo.address != null && photo.address!.isNotEmpty)
                  pw.Text(photo.address!, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
                if (photo.latitude != null)
                  pw.Text(
                    '${photo.latitude!.toStringAsFixed(4)}, ${photo.longitude!.toStringAsFixed(4)}',
                    style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
                  ),
                if (photo.memo != null && photo.memo!.isNotEmpty)
                  pw.Container(
                    margin: const pw.EdgeInsets.only(top: 4),
                    padding: const pw.EdgeInsets.all(6),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.grey100,
                      borderRadius: pw.BorderRadius.circular(4),
                    ),
                    child: pw.Text(photo.memo!, style: const pw.TextStyle(fontSize: 9)),
                  ),
                if (photo.weatherInfo != null && photo.weatherInfo!.isNotEmpty)
                  pw.Text('${s['weather']}: ${photo.weatherInfo!}',
                      style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              ],
            ),
          ),
        );
      }

      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: widgets,
          ),
        ),
      );
    }

    // 저장
    final tempDir = await getTemporaryDirectory();
    final now = DateTime.now();
    final fileName = 'exacta_report_${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}.pdf';
    final filePath = p.join(tempDir.path, fileName);
    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    return filePath;
  }
}
